package v1

import (
	imageController "halo-suster/internal/delivery/http/v1/controller/image"
	userController "halo-suster/internal/delivery/http/v1/controller/user"
	userService "halo-suster/internal/service/user"
	cryptoJWT "halo-suster/package/crypto/jwt"

	"github.com/go-playground/validator/v10"
	"github.com/jmoiron/sqlx"
	echojwt "github.com/labstack/echo-jwt/v4"
	"github.com/labstack/echo/v4"

	_ "halo-suster/cmd/docs" // docs is generated by Swag CLI, you have to import it.
)

func Init(app *echo.Echo, db *sqlx.DB, val *validator.Validate) {
	var (
		userSvc = userService.New(db)
	)

	//Init JWT
	jwt := echojwt.WithConfig(cryptoJWT.JWTConfig())

	v1 := app.Group("/v1")
	imageController.Init(v1, val)
	userController.Init(v1, val, userSvc, jwt)
}
