name: Build and Publish

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build the Docker Image
        run:  docker build -f ./deploy/Dockerfile -t malikilamalik/halo-suster:${{ github.sha }} .